#A simple chat games project for Learn spigot

Questions:
   1:
      question: 'Who is the Potato king of Minecraft?'
      answer: 'Technoblade'

   2:
      question: 'What can you wear to stop Enderman attacking you?'
      answer: 'pumpkin'

   3:
      question: 'Where is Mojang based?'
      answer: 'Sweden'

   4:
      question: 'which was the first minecraft mob?'
      answer: 'Creeper'
